apiVersion: apps/v1
kind: Deployment
metadata:
  name: bezkoder-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bezkoder-api
  template:
    metadata:
      labels:
        app: bezkoder-api
    spec:
      containers:
        - name: api
          image: vinuthnakoganti/backend:v1   # Replace with your Docker Hub image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: mongo-secret
