apiVersion: v1
kind: Service
metadata:
  name: bezkoder-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: bezkoder-api
  ports:
    - port: 8080         # cluster internal port
      targetPort: 8080   # container port
      nodePort: 32080    # external port to access from EC2

