apiVersion: v1
kind: Service
metadata:
  name: bezkoder-ui-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: bezkoder-ui
  ports:
    - port: 80         # internal port
      targetPort: 80  # container port
